### ISSUE TITLE
Adopt WCAG 2.0 AA

### ISSUE THREAD

**Issue by mfairchild365** [18F/accessibility#135]
I would like to challenge 18F to officially adopt the WCAG 2.0 standard for accessibility, specifically WCAG 2.0 level AA. The 18F documentation currently focuses on the section 508 standard which is ~18 years old. WCAG has, for the most part, taken place of the 508 standard for modern web development.

WCAG covers every aspect of the 508 standard. There are a few cases where 508 is more specific. However, there are more cases where WCAG is more specific or equivalent. More importantly, WCAG covers more points than 508 and thus provides a better level of accessibility. See http://jimthatcher.com/sidebyside.htm

Furthermore the Department of Justice and the Office for Civil Rights have issued several settlements requiring the minimum use of WCAG 2.0 level AA. Those settlements and resolution agreements include, but are not limited to:

- peapod, LLC: https://www.justice.gov/file/163956/download
- Louisiana Tech (2013): http://www.ada.gov/louisiana-tech.htm

Over the past several years, the United States Access Board has been working to update Section 508 to incorporate WCAG: https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/overview-of-the-proposed-rule

As further proof, 18F has said that they use WCAG 2.0, however there is no mention of WCAG in this repository. See https://twitter.com/18f/status/672836986814775296 

As a federal org, I realize the need to keep the 508 standard. However, there is no reason that 18F can not meet both standards

**Comment by mwolff-unl** [comment]
I feel like this is especially important. The US should set a good example to the rest of world and its own US-based sites.

**Comment by nickbristow** [comment]
@mfairchild365 
Hi Michael,

So I have been pushing the team to meet WCAG 2.0 AA standards here at 18f for awhile now, but you are correct it is not explicitly stated on the guide so I will address that. 

We are still required to adhere to section 508 law, but we can follow section 508 standard 1194.5, which allows us to use WCAG as our standards. 

I will make an update to the home page of the guide pointing this out.

**Comment by mfairchild365** [comment]
Ah, 1194.5 is perfect. The updates that you described sound promising, I'm looking forward to seeing them. Please let me know if there is any way that I can help.

**Comment by nickbristow** [comment]
https://github.com/18F/accessibility/pull/138

closing
