### ISSUE TITLE
Accessibility Guide Checklist Importance

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#136]
Noticed while reading the Accessibility Guide's Checklist page ( https://pages.18f.gov/accessibility/checklist/ ) that the following sentence is incorrect - "**It's broken down into three sections of decreasing import: A, B and C.**" Shouldn't it be "**decreasing IMPORTANCE**" instead of "**decreasing IMPORT**"?

Also, of more importance to that grammar issue above is the items under the heading **"B - Less critical issues**" you state below that they are overcome mostly by assistive technology when most of them (first five) are foresighted user and those using a keyboard, which are not assistive technologies.

**B - Less critical issues that can be overcome by most assistive technology**

**Comment by nickbristow** [comment]
Once again, thanks for the feedback.

With this list, i was really trying to come up with categories that would allow a dev to go through A and that alone would help >75% of AT users, then B would get 20%, and C would get the last 5%. 

Here's a PR, let me know what you think. 

https://github.com/18F/accessibility/pull/139/files

**Comment by nickbristow** [comment]
I'm going to merge that PR. If you have any other suggestions to make that checklist better, please let me know or submit a PR. 

Always appreciate it.
