### ISSUE TITLE
Accessibility Guide Tools

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#137]
While looking over the Accessibility Guide's Tools page, I noticed under the "**Accessibility Checkers**" section you did not have the Web Accessibility Toolbar (WAT) for IE that the DHS Trusted Tester process/program uses to do their testing with, which other government agencies are starting to use too.

The Web Accessibility Toolbar (WAT) has been developed to aid manual examination of web pages for a variety of aspects of accessibility. More can be found here on the Paciello Groups website - https://www.paciellogroup.com/resources/wat/

**Comment by nickbristow** [comment]
Ah yes, my old friend WAT. added! 
https://github.com/18F/accessibility/commit/b4c483495601bde0e49f30e5af7f8258947ff496
