### ISSUE TITLE
Incorrect guidance on headings (h1's and h2's)

### ISSUE THREAD

**Issue by maya** [18F/accessibility#145]
https://pages.18f.gov/accessibility/headings/ states:
>When using headings, it is best practice to reserve `<h1>` for the name of the site, `<h2>` for the page title.

but this is not correct, site titles or logos should use an `<em>` tag and `<h1>` should be the page title. @nickbristow

**Comment by nickbristow** [comment]
https://github.com/18F/accessibility/pull/146

**Comment by selfthinker** [comment]
Just for the record, although using an `h1` only for the page title is common best practice, it is not the only acceptable solution. The W3C mentions in its Web Accessibility Tutorial about [headings and page structure](https://www.w3.org/WAI/tutorials/page-structure/headings/) that the initial suggestion to use the `h1` for the site name and `<h2>` for the page title would also be fine.

That doesn't mean that you should recommend it but it's at least not incorrect.

> site titles or logos should use an `<em>`

I've added a comment regarding that to #221.

**Comment by selfthinker** [comment]
Oh, I just realised that this Accessibility Guide is actually not following its own guidance and is using an `h1` for the site title and an `h2` for each page title. As I said, I don't think that's wrong as such. But in this case it might be more important to add that as another valid example and mention both.
