### ISSUE TITLE
consolidate tool and learning resources

### ISSUE THREAD

**Issue by afeld** [18F/accessibility#154]
There are some tools and learning resources listed on [the homepage](https://accessibility.18f.gov/), but also on https://accessibility.18f.gov/tools/ and https://accessibility.18f.gov/training-videos/, respectively. Might want to consolidate them, so we aren't maintaining lists multiple places. Thanks!

**Comment by carodew** [comment]
Good points. We're currently talking to some folks around 18F about what they need in terms of support for building accessible websites and once we have that data, we'll take another look at the guide and see where we can make improvements. Keeping this open as a reminder when we get there.

**Comment by afeld** [comment]
Bump 😃

**Comment by afeld** [comment]
Apparently there is also https://engineering.18f.gov/accessibility-scanning/. cc @Sgtpluck

**Comment by afeld** [comment]
Larger issue around consolidating sites: https://github.com/GSA/accessibility-for-teams/issues/44

**Comment by iamjolly** [comment]
Thanks @afeld. That one has had some attention indirectly via a team at GSA working on an [Accessibility Content Rationalization project 🔒 ](https://drive.google.com/drive/folders/0ADi8NF-jsm9hUk9PVA). 

I need to check on movement of that project to see if we/they are at any decision points about sites and content within them. My sense is that moving to have one GSA resource for all of this won't happen soon, and it may not be totally practical—at least for now.
