### ISSUE TITLE
recommend AccessLint?

### ISSUE THREAD

**Issue by afeld** [18F/accessibility#155]
https://robots.thoughtbot.com/introducing-accesslint-web-accessibility-testing-in-ci

and maybe

https://github.com/dequelabs/axe-core

?

**Comment by maya** [comment]
@afeld we've added it to the list of tools here: https://github.com/18F/accessibility/pull/159 as well as using it on this repo. Is there anything else you'd like to see?

**Comment by afeld** [comment]
Great! Thoughts about mentioning the underlying tool?

https://github.com/dequelabs/axe-core

**Comment by maya** [comment]
Either way is fine. We're not mentioning the underlying engines for the other tools and people can always read more about it by following the link, but we can also add something in. Feel free to submit a PR if you think it's helpful!

**Comment by afeld** [comment]
Nah, that works for me. Thanks!
