### ISSUE TITLE
Clip method for skip links preferred?

### ISSUE THREAD

**Issue by sunnywalker** [18F/accessibility#157]
Re: https://pages.18f.gov/accessibility/links/
It's my understanding that the negative margins `left: -10000;` for visually hiding text is undesirable because it creates a much larger rendering canvas which can eat up memory and can be troublesome on mobile. Perhaps promoting the clipped/collapsed method as described in https://snook.ca/archives/html_and_css/hiding-content-for-accessibility or as used by the HTML5 Boilerplate http://stackoverflow.com/a/20130500 would be preferred.

**Comment by nickbristow** [comment]
Nice, I hadn't seen that. 

Will update recommendation.

**Comment by nickbristow** [comment]
https://github.com/18F/accessibility/pull/161
