### ISSUE TITLE
Search results link to dead pages

### ISSUE THREAD

**Issue by nickbristow** [18F/accessibility#180]
When using search, the results links don't work properly

**Comment by maya** [comment]
@nickbristow that's bc the link URL is https://pages.18f.gov/site/18f/accessibility/checklist/ instead of https://pages.18f.gov/accessibility/checklist/. We need to remove `site/18f/` from the search result link URL to get it to work.

**Comment by BlancEleven** [comment]
@maya Could this be in the jekyll_pages_api somewhere? The search links work perfectly when hosted locally.

**Comment by maya** [comment]
This is an issue with the plugin and how it's using the site baseurl. It will be resolved once we move off of 18F Pages.

**Comment by nkkl** [comment]
This is working correctly now, presumably based on the move Maya mentioned.
