### ISSUE TITLE
Add accessible color palette builder

### ISSUE THREAD

**Issue by gemfarmer** [18F/accessibility#181]
@ericronne mentioned to me that it could be cool to add @toolness's nifty [accessible color palette builder](https://toolness.github.io/accessible-color-matrix/) to the 18F accessibility guide to showcase our dedication to accessible sites.

**Considerations**: 

- the palette builder is static, so it could be supported within the guides.
- it is built in Elm, which isn't one of 18F's core languages, and therefore could be problematic to maintain over time. I wouldn't want this to get in the way of deployment, but definitely worth considering.
- Could live in the [Color and contrast section](https://guides.18f.gov/accessibility/color/) of the guides or be as standalone Federalist app that is referenced in the [tools section](https://guides.18f.gov/accessibility/tools/).

**Comment by ericronne** [comment]
This Eight Shapes [contrast analyzer tool](http://contrast-grid.eightshapes.com/?background-colors=&foreground-colors=%23FFFFFF%2C%20White%0D%0A%23F2F2F2%0D%0A%23DDDDDD%0D%0A%23CCCCCC%0D%0A%23888888%0D%0A%23404040%2C%20Charcoal%0D%0A%23000000%2C%20Black%0D%0A%232F78C5%2C%20Effective%20on%20Extremes%0D%0A%230F60B6%2C%20Effective%20on%20Lights%0D%0A%23398EEA%2C%20Ineffective%0D%0A&es-color-form__tile-size=compact) is robust, a good reference.

**Comment by ericronne** [comment]
@austinhernandez fyi

**Comment by ericronne** [comment]
@toolness

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
