### ISSUE TITLE
AccessLint AMA

### ISSUE THREAD

**Issue by gemfarmer** [18F/accessibility#182]
### Exciting updates!!
AccessLint (maintained by thoughtbot) recently decided to create a standalone version of their existing tool that isn't reliant on CircleCI or other continuous integration tools. This is great for the world, but especially exciting for 18F as we may discontinue using CircleCI in the near future. 

Folks from AccessLint have agreed to talk to the Accessibility guild about upcoming development on a new standalone (not reliant on CircleCI) version of AccessLint. This is an issue to house that discussion.

### What is AccessLint?

From [the site](https://github.com/accesslint/accesslint-c):

> Runs accesslint-cli in CircleCI and comments on GitHub pull requests with new accessibility issues.
> 
> accesslint-ci will crawl a host site and run accessibility assertions on the pages. If there are any new accessibility issues, accesslint-ci will comment on the pull request that initiated the build in CircleCI.

AccessLint is fundamentally different than [`pally-ci`]() because it uses [axe-core](https://github.com/dequelabs/axe-core) under the hood and checks a live version of the built site, instead of _predicting_ accessibility errors. This should reduce false negatives and make addressing accessibility errors more productive.

### 18F sites currently using AccessLint:
* [18f.gsa.gov](https://github.com/18F/18F.gsa.gov)
* [Accessibility guild](https://github.com/18F/accessibility)
* ??

### Resources:

* [Github](https://github.com/accesslint/accesslint-ci)
* [Introducing AccessLint (thoughtbot article)](https://robots.thoughtbot.com/introducing-accesslint-web-accessibility-testing-in-ci)
* [Slack channel](https://accesslint.slack.com)
* [Twitter](https://twitter.com/accesslint)
* [Website (where you can get an API key)](https://accesslint.com/)

cc @tysongach @ckundo

**Comment by gemfarmer** [comment]
@shawnbot & @juliaelman Your names came up in the meeting. 😺  @ckundo and @tysongach are interested in using the [web-design-standards-docs](github.com/18F/web-design-standards-docs/) project as a pilot for the new standalone AccessLint service!

**Comment by juliasolorzano** [comment]
@gemfarmer that is fantastic news and thanks for the ping!

**Comment by gemfarmer** [comment]
I'm going to be working to get approval for the pilot. It looks like we will need to make a purchase request via Communicart :(

https://handbook.18f.gov/purchase-requests/
https://gsa-tts.slack.com/archives/infrastructure/p1489170625243503
https://gsa-tts.slack.com/archives/infrastructure/p1489171144358189

Summary: It looks like I will need to ask @afeld to submit a purchase request before this pilot can official start.

**Comment by afeld** [comment]
Closing as stale.
