### ISSUE TITLE
Forms.md - "find all instructions", could be more specific in what constitutes instructions

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#184]
Under testing: 

Find all instructions associated with each element.
    If a form element isn't programatically associated with ALL instructions, this is a failure.

It isn't clear from this what constitutes all instructions - it could be expanded to say "this includes egends, labels, hint text  and tooltips ". 

This may also benefit from including detail about fieldsets and optgroups

**Comment by nickbristow** [comment]
Updated https://github.com/18F/accessibility/blob/18f-pages/pages/forms.md
