### ISSUE TITLE
Images.md - repeated images

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#192]
Says to check that repeated images have the same alt text. Whilst that would generally be true it could depend on context. In some cases an image might be repeated on a page but with a different meaning.

**Comment by nickbristow** [comment]
This is actually a holdover from the DHS test process which requires all duplicate images have the same alt text. Its derived from section 508 1194.21(e). Which is more specifically pertaining to controls and programatic elements. 

I'll make a note as such on the page.
