### ISSUE TITLE
Images.MD - All text in the image is included in the alt text

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#193]
Says to test that "All text in the image is included in the alt text" - that depends on context, some text may be decorative or unimportant, and the meaning of the image may not be the same as the literal text.

**Comment by nickbristow** [comment]
This is a requirement for DHS's trusted tester program. I've made note of that on the page. https://github.com/18F/accessibility/blob/18f-pages/pages/images.md
