### ISSUE TITLE
color.md - clarity on lightest/darkest combinations

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#199]
Might help to specify that the lightest part of the text should be tested against the lightest part of the background and the darkest part of the text against the darkest part of the background. Normally it would only be backgrounds that had gradients, patterns or images though so it might be simpler to just say check light text against the lighest part of its background, and dark text against the darkest part of its background.

**Comment by nickbristow** [comment]
updated https://github.com/18F/accessibility/blob/18f-pages/pages/color.md
