### ISSUE TITLE
tables.md - scope=row and scope=column not required

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#203]
Says that each table header cell should have scope=row or scope=col and also says to test for this - research shows that use of these attributes makes no difference for assistive technology so they are not required.

**Comment by nickbristow** [comment]
While this is true, certain test procedures in the federal government still require these attributes. I've made a note for users who might not be building for the federal government. 
https://github.com/18F/accessibility/pull/209

**Comment by accessiblewebuk** [comment]
That's great - I didn't know about the requirement
