### ISSUE TITLE
headings.md - references to document outline order

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#204]
says "Other (than h1) heading levels may be used more than once following document outline order and you may reset headings up to h2 with the section element." - user agents don't support this and there is no sign of plans for it to be supported.

**Comment by nickbristow** [comment]
I've read some conflicting stuff. The HTML 5 standards don't spell it out directly, https://www.w3.org/TR/html5/sections.html#the-section-element, 

But people have interpreted it as, `you should reset to h1 in each section and article`
http://webmasters.stackexchange.com/questions/8577/html5-semantics-h1-or-h2-for-article-titles-in-a-section

I think when I wrote this, I suggested only going to H2 in sections as older browsers wouldn't interpret the page outline correctly. The text is a bit confusing.

**Comment by nickbristow** [comment]
Hows this https://github.com/18F/accessibility/pull/208

**Comment by accessiblewebuk** [comment]
I think this makes things clear: https://www.w3.org/TR/html5/sections.html#outlines - says "Warning - There are currently no known implementations of the outline algorithm in graphical browsers or assistive technology user agents, although the algorithm is implemented in other software such as conformance checkers. Therefore the outline algorithm cannot be relied upon to convey document structure to users. Authors are advised to use heading rank (h1-h6) to convey document structure." and it is referenced in https://www.paciellogroup.com/blog/2013/10/html5-document-outline/ by @stevefaulkner

**Comment by nickbristow** [comment]
Updated https://github.com/18F/accessibility/blob/18f-pages/pages/headings.md
