### ISSUE TITLE
properties.md

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#213]
It isn't clear why the page is called Web Text Properties - don't know most people would equate this with setting the language. Would suggest the page should just be called and headed "Language" unless there is a specific need for the term Web Text Properties.

**Comment by nickbristow** [comment]
Lol. yeah, i figured i'd have more content here about meta data on the page.

**Comment by nickbristow** [comment]
https://github.com/18F/accessibility/pull/219
