### ISSUE TITLE
css.md background images and tagging 

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#216]
says "background images can't be tagged for accessibility". To avoid confusion with tags, elements and attributes it might be better to say "background images can't have alt attributes, so if they contain important information they should either have alternative text elsewhere within the page content, or preferably be coded as image elements with alt text".

**Comment by nickbristow** [comment]
Updated https://github.com/18F/accessibility/blob/18f-pages/pages/css.md
