### ISSUE TITLE
Fix contrast on "Home" link

### ISSUE THREAD

**Issue by adelevie** [18F/accessibility#22]
![screen shot 2015-03-03 at 2 52 11 pm](https://cloud.githubusercontent.com/assets/86790/6470900/fab252d0-c1b4-11e4-8510-05e23f41a380.png)

**Comment by mbland** [comment]
The style has changed a bit since this issue was filed; is it relevant anymore, or does the new style resolve the issue?

**Comment by mhokane** [comment]
Yeah I think it's OK actually. The current gray passes for large text. 
![image](https://cloud.githubusercontent.com/assets/5339354/9722489/cceca802-5573-11e5-8df4-6d89d8759144.png)

**Comment by maya** [comment]
The nav link styles have changed a while ago, so this is no longer a problem.
