### ISSUE TITLE
headings.md - use of <em> for text logos

### ISSUE THREAD

**Issue by accessiblewebuk** [18F/accessibility#221]
Where does the advice "For logos that are text-based, use `<em>` element." originate from and what is the purpose of it? Screenreaders don't generally provide support for <em>

**Comment by selfthinker** [comment]
This text was added after @maya claimed that in #145. I also find it odd and would like to know where it is coming from. I would think many more elements would be fine for a logo (from a span or a strong to a div or a p), it doesn't matter much as long as it doesn't give the wrong meaning.

**Comment by maya** [comment]
@selfthinker @accessiblewebuk The idea for using `<em>` comes from https://csswizardry.com/2010/10/your-logo-is-an-image-not-a-h1/#what-if-you-dont-have-a-logo. This would allow the screen reader to read the site title with emphasis.

@selfthinker I think I agree that is could be other elements like you suggested.

**Comment by accessiblewebuk** [comment]
@maya @selfthinker `<em>` isn't supported by screenreaders - see https://www.paciellogroup.com/blog/2008/02/screen-readers-lack-emphasis/ - there is no advantage in using `<em>` as far as screenreaders go. This advice should probably therefore be removed.

**Comment by nickbristow** [comment]
I've made a PR to clarify this recommendation 
https://github.com/18F/accessibility/pull/224

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
