### ISSUE TITLE
Wrong use of blockquote (`>`) and code (`)

### ISSUE THREAD

**Issue by selfthinker** [18F/accessibility#226]
Blockquotes (`>`) are used wrongly throughout a lot of the pages. It is never used correctly. When it should be used and something is quoted, `<code>` (i.e. `) is used instead (which is also semantically incorrect).
I can make a PR fixing it but I just wondered what the reason for that is?

I can imagine blockquote is used because Markdown doesn't have any syntax to highlight something. But then again, your template doesn't highlight quoted text, it just gives it a left margin. If you wanted to highlight something, I can think of two solutions for this:

Either slightly misuse the combination of other syntax, e.g. `em` and `strong` together would not make something italic and bold but just highlight the text.
Or use HTML (e.g. just `<div class="highlight or whatever">` or maybe even `<mark>`). The trouble with that is that not all Markdown flavours allow Markdown inside HTML. I know Kramdown allows that with a [`markdown` attribute](https://kramdown.gettalong.org/syntax.html#html-blocks), but you're currently using Redcarpet. There might be solutions for that but as far as I can tell, they wouldn't be as straightforward.

I didn't want to change the code syntax to blockquotes either because if you're using blockquotes for a reason it might have unexpected consequences.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
