### ISSUE TITLE
Skip to Main & Hidden on Focus

### ISSUE THREAD

**Issue by mgifford** [18F/accessibility#238]
It would be good to define the best practice of exposing content on keyboard focus so that things like skip links can be incorporated into pages. 

https://github.com/18F/accessibility/blob/18f-pages/pages/hiddencontent.md

We've included a good example from Drupal
https://www.drupal.org/docs/7/creating-accessible-themes/hide-content-properly

**Comment by mgifford** [comment]
Also worth noting that the `aria-hidden='false'` should probably just be removed. It's not very well supported https://developer.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
