### ISSUE TITLE
Builds failing post jekyll upgrade

### ISSUE THREAD

**Issue by amirbey** [18F/accessibility#246]
1. @nkkl l looks like this https://github.com/18F/accessibility/pull/243 PR has broken the builds when running "jekyll b"
2. commits to this site are no longer appearing on Federalist ... my assumption is the webhook needs to be verified/updated

**Comment by nkkl** [comment]
I don't really understand this enough to even begin fixing it. :(

**Comment by nkkl** [comment]
@Jacklynn can we rally the guild to get a dev to help with this?

**Comment by amoose** [comment]
The webhooks are receiving a 405 (from Federalist):
```
Headers
Allow: GET, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 422
Content-Type: text/html; charset=utf-8
Date: Mon, 28 Oct 2019 23:41:24 GMT
Strict-Transport-Security: max-age=31536000
Via: 1.1 c6b0xxxxxxxxxxxxx.cloudfront.net (CloudFront)
X-Amz-Cf-Id: syCmxxxxxxxxxxxxxx
X-Amz-Cf-Pop: IAD89-C1
X-Cache: Error from cloudfront
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: e65xxxxxxx-xxxxxxxxxx
X-XSS-Protection: 1; mode=block
Body
<html>
<head><title>405 Method Not Allowed</title></head>
<body>
<h1>405 Method Not Allowed</h1>
<ul>
<li>Code: MethodNotAllowed</li>
<li>Message: The specified method is not allowed against this resource.</li>
<li>Method: POST</li>
<li>ResourceType: OBJECT</li>
<li>RequestId: 67Axxxxxxxxxx</li>
<li>HostId: 3jEoxxxxxxmxxxxxxxx</li>
</ul>
<hr/>
</body>
</html>
```

**Comment by amirbey** [comment]
do your webhook settings appear same as the screenshot? the payload url in particular?
<img width="753" alt="Screen Shot 2019-10-29 at 9 40 50 AM" src="https://user-images.githubusercontent.com/1261794/67772324-41279c80-fa30-11e9-988e-bda1a0e860f7.png">

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
