### ISSUE TITLE
Naming of the guide

### ISSUE THREAD

**Issue by adunkman** [18F/accessibility#265]
:wave: Hi folks! 

Whereas I believe this is a product of Accessibility Guild, and whereas Guilds are TTS-wide groups, I think this guide is qualified to be called the "TTS Accessibility Guide" instead of being 18F-specific. 

This would be beneficial to qualify as a TTS-level resource to:
- Help increase standardized accessibility practices across TTS.
- Clarify that contributions towards this guide are considered TTS engagement activities for the purposes of performance plans.
- Probably other things that I’m not writing down. 

Thoughts? There’s prior art here in https://engineering.18f.gov.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
