### ISSUE TITLE
"Links that open in a New Window" guidance improvement

### ISSUE THREAD

**Issue by aduth** [18F/accessibility#266]
URL: https://accessibility.18f.gov/links/

A couple possible concerns I've noted for the content of the "Links that open in a New Window" guidance:

- An `aria-label` of only "Opens in new window" would override and prevent any content of the link from being read, thus not informing the user where the link would take them.
  - Suggestion: Update example to `aria-label="18F Accessibility Guide (Opens in new window)"` or comparable
- May consider excluding an example using `title` altogether. My understanding is that [given its many flaws](https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/) it's not worth using `title` at all in place of one of the alternatives.
  - Suggestion: Remove second example.
- Should an example including visual indication be included, potentially as the primary recommendation? From [G201 Procedure](https://www.w3.org/TR/WCAG20-TECHS/G201.html): "Check that there is a visual warning in text that this link opens to a new window."
- Should we include guidance that it's best to avoid opening links in new windows except in qualifying circumstances? ([G200](https://www.w3.org/TR/WCAG20-TECHS/G200.html))
  - Possibly incorporate or reference in the first step "Identify links that open in new windows"

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
