### ISSUE TITLE
Broken Link on the 18F Accessibility Guide Home Page

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#284]
On the 18F Accessibility guide home page ( https://accessibility.18f.gov/ ), the  Access Board’s Section 508 Standards for EIT ( https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-section-508-standards/section-508-standards ) link gets a page not found for the U. S. Access Board website.

**Comment by christophermather** [comment]
Closing since this appears to have been addressed via https://github.com/18F/accessibility/commit/d6d25166ed1a3bb1ebf4beb6c2c15331bebc4ef7
