### ISSUE TITLE
Incorrect LABEL FOR and INPUT Field ID on the 18F Accessibility Guide Forms Page

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#288]
On the 18F Accessibility Guide Forms page ( https://accessibility.18f.gov/forms/ ),  there is an incorrect LABEL FOR and INPUT Field ID combination for "1lastname" because it starts with a number if I'm not mistaken and should be added to the failures or things have changed.

**Comment by iamjolly** [comment]
You are correct! Things have changed from HTML4 to the HTML5 spec regarding `id` content rules. 

The [current HTML5 spec for the `id` attribute](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute) states:
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
