### ISSUE TITLE
Correct Content on the 18F Accessibility Guide iframes Page

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#296]
On the 18F Accessibility Guide iframes Page ( https://accessibility.18f.gov/iframes/ ), under the "Testing" heading and other places in the page, you refer to iframes, but for list items 2 and 3, you use frame. Should we list them as "iframes/frame" or at least be consistent when referring to them and use one or both.

**Comment by iamjolly** [comment]
Since `frame` and `frameset` were [removed as obsolete from HTML5](https://www.w3.org/TR/html5-diff/#obsolete-elements), I think we should change these to `iframe` in the content. 

Thanks for catching all these inconsistencies and problems @jfc3-dol. You are *very* appreciated!

**Comment by jfc3-dol** [comment]
@iamjolly,

You're welcome.

I figured while I was in reading the information and found anything, I would pass it on to help improve it for others.

Good luck with all the other ones I submitted. :)
