### ISSUE TITLE
Are Plugins Necessary on the 18F Accessibility Guide?

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#299]
Are plugins necessary as part of the 18F Accessibility Guide ( https://accessibility.18f.gov/plugins/ ) after the Section 508 refresh? And do other things need to be updated in this guide because of the refresh?

**Comment by iamjolly** [comment]
> Are plugins necessary as part of the 18F Accessibility Guide ( https://accessibility.18f.gov/plugins/ ) after the Section 508 refresh? 

Probably not needed any more. I'll remove this page entirely. Thanks!

> And do other things need to be updated in this guide because of the refresh?

Maybe? Since the refresh, all the content and guidance should align to WCAG 2.0 AA at the minimum. There may be other instances of outdated guidance, so we should review for any content that should either be updated or removed.
