### ISSUE TITLE
Instructions for generating and running site locally are out of date

### ISSUE THREAD

**Issue by zkamvar** [18F/accessibility#312]
In the README, the command for cloning and previewing the repository is:

```bash
$ git clone https://github.com/18F/accessibility.git accessibility
$ cd accessibility
$ ./go serve
```

However, there is no `go` script in the repository and it appears that the [`go_script` project is archived](https://github.com/18F/go_script)

I have found that using the following lines from the circle-ci configuration works for serving the repository (noting that it takes a bit to install the gems):

https://github.com/18F/accessibility/blob/879e952c251138de2059cc35b8ddf1212093ff84/.circleci/config.yml#L17-L19

```bash
git clone https://github.com/18F/accessibility.git accessibility
cd accessibility
gem install bundler
bundle install
bundle exec jekyll serve
```

I'm happy to submit a PR with these changes if you would like.

**Comment by cannandev** [comment]
Thanks to @Sgtpluck's PR https://github.com/18F/accessibility/pull/315, this has been fixed! Closing this issue. Thanks for submitting @zkamvar
