### ISSUE TITLE
Move/redirect to pages.18f.gov

### ISSUE THREAD

**Issue by konklone** [18F/accessibility#44]
Saw [this tweet](https://twitter.com/lippytak/status/604789055910313985) and was reminded that it's time to get this over to [18F Pages](https://18f.gsa.gov/2015/05/14/18Fpages/).

**Comment by jeremiak** [comment]
We had another incident of confusion today around the right URL to use and how to change the content ([slack conversation](https://18f.slack.com/archives/g-accessibility/p1440016643000416)).

Given that we wouldn't want to break URLs that have been shared in the past, I'd think we might just want to put a `<meta>` tag on the index page on `gh-pages` branch to redirect to our `18f-pages` guide, or we can set something up where Travis merges `18f-pages` to `gh-pages` and pushes back to Github to keep the two up to date.

Preferences, thoughts, queries, concerns?

**Comment by konklone** [comment]
> Given that we wouldn't want to break URLs that have been shared in the past,

Is it that big of a deal? Has it been shared so widely yet?

**Comment by mbland** [comment]
I'd go with the `<meta>` redirect approach. There are reasons we moved off of the .io domain: https://18f.gsa.gov/2015/05/14/18Fpages/.

**Comment by jeremiak** [comment]
@konklone if it's not a big deal then I say we just delete the `gh-pages` branch and let it be.

Otherwise, I submit #61 for your consideration.
