### ISSUE TITLE
Incorrect Accessibility Guide Information about Headings/Headers

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#72]
While reading the 18F Accessibility Guide, I noticed that you have a section on **HEADERs**, which I think you might have meant to be **HEADINGs**. 

See the following URLs  - https://pages.18f.gov/accessibility/headers/ along with the Checklist page - https://pages.18f.gov/accessibility/checklist/.

What **HEADERs** mean to me would be represented by the **HTML5 HEADER** element on this page from the HTML5 Doctor - http://html5doctor.com/the-header-element/ that are a section of an HTML page that is at the beginning of the page and would typically, contain website logo/URL, other information about the website, possibly navigation, etc.

You are referring to **HEADERs** as **HEADINGs** in your Accessibility Guide, but the content in the pages are about **HEADINGs** such as h1, h2, h3, etc.

**Comment by nickbristow** [comment]
Thanks @jfc3-dol will fix that

**Comment by jfc3-dol** [comment]
Thanks.

Hopefully, you can look at my other issues (72 -81) for other suggestions I made to see if they make sense.

**Comment by nickbristow** [comment]
@jfc3-dol looking at them now. 

Thanks for the review! I really appreciate it.
