### ISSUE TITLE
Improper TABLE Heading Code

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#73]
While reading the 18F Accessibility Guide, I noticed that you are making **TABLE HEADINGs** for the peoples names but have them as **TD** (table data) instead of **TH** (table heading) on the **TABLEs** page - https://pages.18f.gov/accessibility/tables/

I have always seen these done as **TH**, which might cause trouble is using CSS to display how the **TABLE** cell should look.

A great article on building accessible **TABLEs** is from Roger Johansson - http://www.456bereastreet.com/archive/200410/bring_on_the_tables/

Look for this information starting after this text - "**Linking headers to data: the scope, id and headers attributes**" to see what I'm talking about.

Also shouldn't **TABLEs** have both a **CAPTION** and a **SUMMARY** statement?

**Comment by mgifford** [comment]
I think you have to do it differently in HTML5.  This is how we implemented it in Drupal 8 https://www.drupal.org/node/843708

**Comment by nickbristow** [comment]
While a caption is very helpful, its not strictly required. I've added a note about it and updated the row spans. 

In html 4 you could do `<td span="row">` but its been deprecated in html 5.
