### ISSUE TITLE
Update "CSS Dependence" Text

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#75]
While reading over this page ( https://pages.18f.gov/accessibility/css/ ) I thought you could give a beet er example for step 3 than "Confusing elements shouldn't be present" and possibly have it say "Confusing elements shouldn't be present such as CSS, JavaScript, or other code, etc."

**Comment by mgifford** [comment]
Who likes "Confusing elements" anyways. I do think this could be clarified as well.  

Plain language, clearly documented functionality, consistent styles, removing jargon....

But also in "Check for code or other items the developer doesn't want you to see", what developer? This is probably mostly a reminder that this is public and so shouldn't have WTF comments in it, even if they are appropriate. 

Mind you this is all in an accessibility document, so confusing to whom? We worried about confusing JAWS?

**Comment by nickbristow** [comment]
Thanks!
