### ISSUE TITLE
Possible Update of Frames Page Text

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#76]
Shouldn't it be "page" instead of "pages" for the following text in step one of testing on the Frames page 9 https://pages.18f.gov/accessibility/frames/ ) "Identify all frames / iframes on a pages", since you are only testing one page at a time?

And shouldn't it be "Using the keyboard, navigate **To** each frame to ensure content is accessible" instead of "Using the keyboard, navigate each frame to ensure content is accessible" in step two?

What about "Check the title or name attribute of each **frame or iframe** for a description of the content"?

**Comment by nickbristow** [comment]
Thanks!
