### ISSUE TITLE
Skipping Heading Levels

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#77]
While looking at your accessibility guide, I noticed that you have two heading level one (h1) on a page, and then the next is a heading level three (h3). Why not make the second heading level one(h1) which is the first heading of the main content section a heading level two (h2), so you don't skip a level,

On your headers page ( https://pages.18f.gov/accessibility/headers/ ) you talk about keeping headings in the proper order.

This issue seems to be on all the pages I looked in your accessibility guide.

**Comment by jfc3-dol** [comment]
Thanks.

Hopefully, you can look at my other issues (72 -81) for other suggestions I made to see if they make sense.

**Comment by nickbristow** [comment]
I believe this has been addressed? I don't see multiple h1's on the page. 

Let me know if you still see an issue.

**Comment by jfc3-dol** [comment]
Looks to me on the random pages I looked at that you corrected the problem.

**Comment by nickbristow** [comment]
thanks

Nick Bristow
18f <http://18f.gsa.gov> Innovation Specialist
Nick.Bristow@gsa.gov

On Tue, Mar 8, 2016 at 4:12 PM, John F Croston III <notifications@github.com
