### ISSUE TITLE
Checking Links Text Change

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#78]
You might want to add text to the issues under step 3 "Unique Links" to mention about the possible off-screen text. An example can be found on the Army's homepage ( http://army.mil/ ) where they visually have "Read more", but have a span that is put visually off-screen that say "about ARTICLE TITLE HERE".

URL - https://pages.18f.gov/accessibility/links/

So the text could read "Check for the title or ARIA attributes to provide context or additional off-screen text" instead of "Check for the title or ARIA attributes to provide context".

Also the word "attribues " is missing a "T"

**Comment by mgifford** [comment]
That's the approach we use in Drupal 7 & 8.  Titles aren't well supported by AT in general. https://www.drupal.org/node/718922

Agreed with the typo.
