### ISSUE TITLE
Visible Skip Navigation Link

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#79]
Does a skip link need to be visible on the page or can it be made visible when a person tabs to it using a keyboard? See step 2 under skip navigation section.

URL - https://pages.18f.gov/accessibility/links/

**Comment by jfc3-dol** [comment]
You might also want to mention why you should put a tabindex='-1' on the ID, which so keyboard focus works for Safari and Chrome or at least older version of them it was an issue.

**Comment by jfc3-dol** [comment]
Further down the page your CSS show the skip link being hidden off-screen which is a contradiction. 

Plus, you should add :active along with :focus for older version of IE.

**Comment by mgifford** [comment]
I'm not sure I've seen a gov websites where "repetitive nav links are not used"

Skip Navigation is pretty much always needed on anything but the most basic site.  It's better if it is exposed all the time, but if not it clearly needs to be enabled on focus.  

@jfc3-dol what version of IE should the be supporting? Hopefully no earlier than IE9

**Comment by nickbristow** [comment]
@jfc3-dol I failed to mention in the text, skip navigation links don't need to be visible at all times, only when they have focus. 

I've updated the text and added the active selector to the css suggestion.
