### ISSUE TITLE
Plug-ins Text Udpate

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#80]
On the plug-ins page you suggest in step 2 of testing the "Identify a link to download each plugin". You can have a link on each page that points to anther page that lists all the plug-ins your website uses, since you might not know what plug-in is need for each page.

URL - https://pages.18f.gov/accessibility/plugins/

**Comment by mgifford** [comment]
Wonder here if it might be useful to suggest HTML5 video over Flash & EPUB over PDF.

There can be good reasons to use those legacy formats, but often it's that they really need to be removed with more modern, mobile ready formats. 

I don't know that VPAT are taken as much more than a sales piece.
