### ISSUE TITLE
Page Navigation Bewteen Sections

### ISSUE THREAD

**Issue by jfc3-dol** [18F/accessibility#81]
It would easier to have a previous and next navigation on your accessibility guide pages or maybe a link to the section before or after the one you are on. Otherwise a person using a keyboard has to tab back to your navigation or scroll up the longer pages to

**Comment by mgifford** [comment]
this would be nice..

**Comment by mbland** [comment]
I've thought about adding this to [18F/guides-style](https://github.com/18F/guides-style/) (the source for the [`guides_style_18f` gem](https://rubygems.org/gems/guides_style_18f) containing the Jekyll layouts and style assets). Just created 18F/guides-style#50 if you care to follow that issue.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
